/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Package_Formulario;

import java.util.Locale;
import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author hp
 */
public class Menu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    Admisiones fromAdmision = new Admisiones();
    Triaje fromTriaje= new Triaje();
    // Cargamos las imágenes desde tu paquete de recursos (ajusta la ruta según tu carpeta)
    javax.swing.ImageIcon iconoClienteOscuro = new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"));
    javax.swing.ImageIcon iconoClienteBlanco = new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario_blanco.png"));

    javax.swing.ImageIcon iconoCitaOscuro = new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario_oscuro.png"));
    javax.swing.ImageIcon iconoCitaBlanco = new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario_blanco.png"));

    private void actualizarEstiloBotones(
            javax.swing.JButton botonActivo,
            javax.swing.JButton botonInactivo,
            javax.swing.ImageIcon iconoActivo,
            javax.swing.ImageIcon iconoInactivo) {

        // --- BOTÓN SELECCIONADO (AZUL) ---
        botonActivo.setContentAreaFilled(true);
        botonActivo.setIcon(iconoActivo); // <--- AQUÍ SE PONE EL ÍCONO BLANCO
        botonActivo.putClientProperty("FlatLaf.style",
                "background: #0061c7;"
                + "foreground: #ffffff;"
                + "borderWidth: 0;"
                + "focusWidth: 0;"
                + "arc: 8;"
                + "iconTextGap: 12");

        // --- BOTÓN DESELECCIONADO (TRANSPARENTE) ---
        botonInactivo.setContentAreaFilled(false);
        botonInactivo.setIcon(iconoInactivo); // <--- AQUÍ SE PONE EL ÍCONO OSCURO
        botonInactivo.putClientProperty("FlatLaf.style",
                "foreground: #445566;"
                + "borderWidth: 0;"
                + "focusWidth: 0;"
                + "arc: 8;"
                + "iconTextGap: 12");

        this.repaint();
    }

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        content.setLayout(new java.awt.BorderLayout());

    }

    private void mostrarPanel(javax.swing.JPanel p) {
        content.removeAll();
        content.add(p, java.awt.BorderLayout.CENTER);

        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_triaje = new javax.swing.JButton();
        btn_admision = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1090, 825));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 224, 230)));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 883, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(244, 248, 252));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 224, 230)));
        jPanel2.setMinimumSize(new java.awt.Dimension(230, 866));
        jPanel2.setPreferredSize(new java.awt.Dimension(230, 866));

        btn_triaje.setBackground(new java.awt.Color(244, 248, 252));
        btn_triaje.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_triaje.setForeground(new java.awt.Color(36, 29, 49));
        btn_triaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario_oscuro.png"))); // NOI18N
        btn_triaje.setText("Triaje");
        btn_triaje.setBorderPainted(false);
        btn_triaje.setFocusPainted(false);
        btn_triaje.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_triaje.setIconTextGap(12);
        btn_triaje.setOpaque(true);
        btn_triaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_triajeActionPerformed(evt);
            }
        });

        btn_admision.setBackground(new java.awt.Color(244, 248, 252));
        btn_admision.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_admision.setForeground(new java.awt.Color(36, 29, 49));
        btn_admision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        btn_admision.setText("Admision");
        btn_admision.setBorderPainted(false);
        btn_admision.setFocusPainted(false);
        btn_admision.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_admision.setIconTextGap(12);
        btn_admision.setOpaque(true);
        btn_admision.setPreferredSize(new java.awt.Dimension(92, 31));
        btn_admision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admisionActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_Posta.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cuidamos tu salud");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_triaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_admision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(btn_admision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_triaje)
                .addContainerGap(601, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_admisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admisionActionPerformed
        // Corregido: Pasamos btn_Registrar_Cita como el botón a "desactivar" visualmente
        actualizarEstiloBotones(btn_admision, btn_triaje, iconoClienteBlanco, iconoCitaOscuro);

        // Obtenemos el panel interno (ContentPane)
        javax.swing.JPanel panelInterno = (javax.swing.JPanel) fromAdmision.getContentPane();

        // Ajustamos tamaño y mostramos
        panelInterno.setSize(content.getSize());
        mostrarPanel(panelInterno);

    }//GEN-LAST:event_btn_admisionActionPerformed

    private void btn_triajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_triajeActionPerformed
     // 1. Actualizamos los estilos: 
    // - El botón activo es 'btn_triaje' (le pasamos icono blanco)
    // - El botón que se desactiva es 'btn_admision' (le pasamos icono oscuro)
    actualizarEstiloBotones(btn_triaje, btn_admision, iconoCitaBlanco, iconoClienteOscuro);

    // 2. Verificamos que 'fromTriaje' esté inicializado
    if (fromTriaje == null) {
        fromTriaje = new Triaje(); // Asegúrate de tener esta variable declarada en tu clase Menu
    }

    // 3. Obtenemos el panel interno y lo mostramos
    javax.swing.JPanel panelInterno = (javax.swing.JPanel) fromTriaje.getContentPane();
    panelInterno.setSize(content.getSize());
    mostrarPanel(panelInterno);
    }//GEN-LAST:event_btn_triajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // FlatLaf toma el control desde la ventana principal
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, "Error FlatLaf", ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_admision;
    private javax.swing.JButton btn_triaje;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
